import React from 'react';
import { Download } from 'lucide-react';
import { motion } from 'framer-motion';
import { Document } from '../types';

interface DownloadReportProps {
  document: Document;
}

export default function DownloadReport({ document }: DownloadReportProps) {
  const handleDownload = () => {
    const reportContent = generateReportContent(document);
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${document.title.toLowerCase().replace(/\s+/g, '-')}-analysis-report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateReportContent = (doc: Document): string => {
    const date = new Date().toLocaleDateString();
    
    return `
LEXIAI DOCUMENT ANALYSIS REPORT
===============================
Document: ${doc.title}
Generated: ${date}
Analyzed: ${doc.clauses.length} clauses
Risks Identified: ${doc.risks.length}

EXECUTIVE SUMMARY
=================
${doc.simplified.map((point, index) => `${index + 1}. ${point}`).join('\n')}

RISK ANALYSIS
=============
${doc.risks.map((risk, index) => `
Risk #${index + 1} - ${risk.risk.toUpperCase()} PRIORITY
Clause: "${risk.excerpt}"
Explanation: ${risk.explanation}
Confidence: ${risk.confidence}
---
`).join('')}

SUGGESTED ACTIONS
=================
HIGH RISKS:
${doc.risks.filter(r => r.risk === 'high').map(r => `• Negotiate different terms for: "${r.excerpt}"`).join('\n')}

MEDIUM RISKS:
${doc.risks.filter(r => r.risk === 'medium').map(r => `• Review and understand: "${r.excerpt}"`).join('\n')}

LOW RISKS:
${doc.risks.filter(r => r.risk === 'low').map(r => `• Be aware of: "${r.excerpt}"`).join('\n')}

DISCLAIMER
==========
This analysis is generated by LexiAI for informational purposes only and does not constitute legal advice. 
For legal action or binding decisions, please consult with a qualified attorney.

Report generated by LexiAI - Legal Made Simple
`.trim();
  };

  return (
    <motion.button
      whileHover={{ scale: 1.02 }}
      whileTap={{ scale: 0.98 }}
      onClick={handleDownload}
      className="flex items-center gap-2 px-4 py-2 bg-gradient-card text-white rounded-xl hover:shadow-lg transition-all duration-200"
    >
      <Download className="w-4 h-4" />
      <span className="font-medium">Download Report</span>
    </motion.button>
  );
}